name: 'Action: PR Titles'
description: Check (and potentially fix) PR titles
author: Bryant Finney <bryant.finney@outlook.com>

branding:
  icon: git-pull-request
  color: blue

inputs:
  title:
    description: The PR title to check (and potentially fix)
    required: true

  prefixes:
    description: A comma-separated list of valid prefixes
    required: true

outputs:
  title:
    description: The PR title after applying fixes

  fixed:
    description: "'true' if the title was fixed; 'false' otherwise"

runs:
  using: node20
  main: dist/index.js
