name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run ci-test

  test-action:
    name: Test the Action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - title: foo 123 change a thing
            fixed: FOO-123 change a thing

          - title: refactor bAr.987
            fixed: refactor BAR-987

          - title: no known prefix
            fail: 'true'

    steps:
      - uses: actions/checkout@v4

      - id: fix
        continue-on-error: ${{ matrix.fail == 'true' }}
        uses: ./
        with:
          title: ${{ matrix.title }}
          prefixes: foo,bar,baz

      - if: ${{ matrix.fail != 'true' }}
        run: '[ "${{ steps.fix.outputs.title }}" = "${{ matrix.fixed }}" ]'

      - if: ${{ matrix.fail == 'true' }}
        run: '[ "${{ steps.fix.outcome }}" = "failure" ]'
