name: Example
on:
  pull_request:
    types: [edited, opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  example:
    env:
      PR_NUM: ${{ github.event.number }}
      GH_TOKEN: ${{ github.token }}

    name: Fix PR Title
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: fix
        uses: ./
        with:
          title: ${{ github.event.pull_request.title }}
          prefixes: foo,bar,baz

      - if: ${{ steps.fix.outputs.fixed == 'true' }}
        run: gh pr edit "$PR_NUM" --title "${{ steps.fix.outputs.title }}"
